repos:
-   repo: local
    hooks:
    -   id: unittest
        name: unittest
        entry: python manage.py test
        language: python
        types: [python]
        stages: [commit]
        pass_filenames: false
        additional_dependencies: ['-r', '/Users/wenyu/Desktop/onlineshop/requirements.txt']
          # additional_dependencies: ['flask_migrate', 'flask_script', 'flask_bcrypt', 'flask_marshmallow', 'flask_restplus', 'marshmallow-sqlalchemy']
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.2
    hooks:
    -   id: autopep8
        name: autopep8
        entry: autopep8
        language: python
        'types': [python]
        args: [--in-place, --aggressive, --aggressive ]
        require_serial: false
        additional_dependencies: []
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -   id: detect-private-key
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-json
    -   id: check-yaml
    -   id: flake8
    -   id: trailing-whitespace
-   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.4
    hooks:
    -   id: python-bandit-vulnerability-check
        args: [-l, --recursive, -x, tests]
        files: .py$
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.6.1
    hooks:
    -   id: reorder-python-imports
